GET http://localhost:3333/events/15a4d285-53d2-4290-8e33-9c14e1412163

###

POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/15a4d285-53d2-4290-8e33-9c14e1412163/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego2@rocketseat.com.br" 
}

###

GET http://localhost:3333/attendees/7/badge

###

GET http://localhost:3333/attendees/7/check-in

###

GET http://localhost:3333/events/15a4d285-53d2-4290-8e33-9c14e1412163/attendees?query=Diego

###