apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19zY3FtLUdTQXRSQjlBRWt5aWhrQHBhc3MtaW4tZG8tdXNlci0xNjI2ODgzNC0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL3Bhc3MtaW4/c3NsbW9kZT1yZXF1aXJlCg==